using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using Hai.Project12.HaiSystems.Supporting;
using Hai.Project12.TF.Runtime;
using UnityEditor;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Hai.Project12.TF.Editor
{
    internal class H12TFCodeGen
    {
        // Declared as consts to prevent unintentional replacements
        private const string __PublicKeyword = "public";
        private const string __PrivateKeyword = "private";

        private const string ObjectsReferencedWithinEventsLabel = "Objects referenced within events";
        private const string PublicFieldsLabel = "Public fields";
        private const string OriginallyNamedLabel = "Originally named";
        private const string ObjectNamedLabel = "named";

        private const bool ShouldRefreshOnCompile = true;
        private const string TEMP__BehaviourClassName = "ExampleBehaviour__00000";
        private const string FieldifiedPrefix = "param_";
        private const bool SupportLegacyPlatform = false;
        private const string BehaviourType = "MonoBehaviour";

        private static readonly Regex NonValidVariableOrFieldNameSymbols = new(@"[^a-zA-Z0-9]+", RegexOptions.Compiled);

        private readonly TFBehaviour _behaviour;
        private readonly Dictionary<string, string> _stVariableOrFieldName = new();
        private readonly Dictionary<Object, string> _fieldifications = new();
        private readonly Dictionary<Object, string> _fieldificationMetadata = new();

        internal H12TFCodeGen(TFBehaviour behaviour)
        {
            _behaviour = behaviour;
        }

        private string DeclareFieldName(string tfFieldName)
        {
            return SanitizeVariableOrFieldName(tfFieldName);
        }

        private string SanitizeVariableOrFieldName(string tfFieldName)
        {
            if (_stVariableOrFieldName.TryGetValue(tfFieldName, out var storedSanitizedName))
            {
                return storedSanitizedName;
            }

            var degradedName = NonValidVariableOrFieldNameSymbols.Replace(tfFieldName, "");
            if (tfFieldName == degradedName)
            {
                _stVariableOrFieldName.Add(tfFieldName, tfFieldName);
                return tfFieldName;
            }
            else
            {
                var prefix = string.IsNullOrWhiteSpace(degradedName) ? "unnamed" : degradedName;
                // We do the Sha1 on the original name, not the degraded one.
                // This is intentional, so that a name like "本文" always gets transformed the same way,
                // and differently to other names that may become degraded in the same way.
                var sanitizedName = $"{prefix}_{H12Utilities.SimpleSha1(tfFieldName)}";
                _stVariableOrFieldName.Add(tfFieldName, sanitizedName);
                return sanitizedName;
            }
        }

        internal void Generate(bool refresh = true)
        {
            var tfRoot = new TFRoot();
            var tfLicense = new TFSection();
            var tfUsings = new TFSection();
            var tfNamespace = new TFBrace("namespace _TFB");
            var tfClassDefinition = new TFSection();
            var tfClass = new TFBrace(null);
            var tfFields = new TFSection();
            var tfMethods = new TFSection();

            // Compose sections
            {
                tfRoot.Add(tfLicense);
                tfRoot.Add(tfUsings);
                tfRoot.Add(new TFEmptyLine());
                tfRoot.Add(tfNamespace);
                tfNamespace.Add(tfClassDefinition);
                tfNamespace.Add(tfClass);
                tfClass.Add(tfFields);
                tfClass.Add(new TFEmptyLine());
                tfClass.Add(tfMethods);
            }

            // License
            {
                tfLicense.Add(new TFLine("// This component class has been generated by TF."));
                tfLicense.Add(new TFLine("// Do not edit this class. Any changes made to this class may be overwritten."));
                tfLicense.Add(new TFEmptyLine());
            }

            // TODO: List of gameobjects need to be turned into fields

            // Fields
            if (_behaviour.fields.Count > 0)
            {
                tfFields.Add(new TFLine($"[Header(\"{PublicFieldsLabel}\")]"));
                foreach (var tfField in _behaviour.fields)
                {
                    string type;
                    switch (tfField.value.targetType)
                    {
                        case TFParameterTargetType.String:
                            type = "string";
                            break;
                        case TFParameterTargetType.Object:
                            type = tfField.value.objectValue.GetType().FullName; // TODO: How to know what type the field should be?
                            break;
                        case TFParameterTargetType.Boolean:
                            type = "bool";
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }

                    var sanitizedName = DeclareFieldName(tfField.name);
                    var comment = sanitizedName == tfField.name ? "" : $" // {OriginallyNamedLabel} \"{SanitizeNameAsSingleLineComment(tfField.name)}\"";
                    tfFields.Add(new TFLine($"{__PublicKeyword} {type} {sanitizedName};{comment}"));
                }
            }

            // Methods
            {
                ProcessEvents(tfMethods);
                // Order matters
                if (_fieldifications.Count > 0)
                {
                    tfFields.Add(new TFEmptyLine());
                    tfFields.Add(new TFLine($"[Header(\"{ObjectsReferencedWithinEventsLabel}\")]"));
                    foreach (var (obj, fieldified) in _fieldifications)
                    {
                        var label = _fieldificationMetadata[obj];

                        var type = obj == null ? typeof(UnityEngine.Object) : obj.GetType();
                        var suffixation = _behaviour.addObjectNamesInCode ? $" // {type.Name} {ObjectNamedLabel} \"{SanitizeNameAsSingleLineComment(label)}\"" : "";
                        tfFields.Add(new TFLine($"[SerializeField] {__PrivateKeyword} {type.FullName} {fieldified};{suffixation}"));
                    }
                }
            }

            // Class definition
            var supportLegacyPlatform = _behaviour.supportLegacyPlatform;
            {
                if (!string.IsNullOrWhiteSpace(_behaviour.description))
                {
                    tfClassDefinition
                        .Add(new TFUnindentedLine("/**"))
                        .Add(new TFUnindentedLine($"{SanitizeMultilineComment(_behaviour.description)}"))
                        .Add(new TFUnindentedLine("*/"));
                }
                if (supportLegacyPlatform) tfClassDefinition
                    .Add(new TFUnindentedLine("#if !TF_IS_BASIS || TF_BASIS_USES_SHIMS"))
                    .Add(new TFLine("[UdonBehaviourSyncMode(BehaviourSyncMode.None)]"))
                    .Add(new TFLine($"{__PublicKeyword} class {TEMP__BehaviourClassName} : UdonSharpBehaviour"))
                    .Add(new TFUnindentedLine("#else"));
                tfClassDefinition.Add(new TFLine($"{__PublicKeyword} class {TEMP__BehaviourClassName} : {BehaviourType}"));
                if (supportLegacyPlatform) tfClassDefinition
                    .Add(new TFUnindentedLine("#endif"));
            }

            // Usings
            {
                tfUsings
                    .Add(new TFLine("using UnityEngine;"));
                // TODO: Add imports

                if (supportLegacyPlatform) tfUsings
                    .Add(new TFUnindentedLine("#if !TF_IS_BASIS"))
                    .Add(new TFLine("using UdonSharp;"))
                    .Add(new TFUnindentedLine("#endif"));
            }

            // We're done

            var tfWriter = new H12TFWriter(new StringWriter(), tfRoot);
            var written = tfWriter.WriteAll();

            File.WriteAllText(Path.Combine(Application.dataPath, $"{TEMP__BehaviourClassName}.cs"), written);

            if (refresh && ShouldRefreshOnCompile)
            {
                AssetDatabase.Refresh();
            }

            RefillFields(TEMP__BehaviourClassName);
        }

        private string SanitizeMultilineComment(string untrustedText)
        {
            string previous;
            var replace = untrustedText;
            do
            {
                previous = replace;
                replace = replace
                    .Replace("/*", "--"); // "//**" must not become "--/*--"
            } while (previous != replace);

            return replace;
        }

        private string SanitizeNameAsSingleLineComment(string untrustedText)
        {
            string previous;
            var replace = untrustedText;
            do
            {
                previous = replace;
                replace = replace
                    .Replace("\r\n", " ")
                    .Replace("\n", " ")
                    .Replace("/*", "--"); // "//**" must not become "--/*--"
            } while (previous != replace);

            return replace;
        }

        internal void RefillFields()
        {
            RefillFields(TEMP__BehaviourClassName);
        }

        private void RefillFields(string behaviourClassName)
        {
            if (H12ComponentDictionary.TryGetComponentType("_TFB." + behaviourClassName, out var generatedType))
            {
                var component = _behaviour.gameObject.GetComponent(generatedType);
                if (component == null) component = _behaviour.gameObject.AddComponent(generatedType);

                foreach (var tfField in _behaviour.fields)
                {
                    // TODO: Non-strings
                    var fieldInfo = generatedType.GetField(SanitizeVariableOrFieldName(tfField.name));
                    if (fieldInfo != null) // Defensive. This may be null if we haven't recompiled the class yet.
                    {
                        var value = tfField.value;
                        switch (value.targetType)
                        {
                            case TFParameterTargetType.String:
                                fieldInfo.SetValue(component, value.stringValue);
                                break;
                            case TFParameterTargetType.Object:
                                fieldInfo.SetValue(component, value.objectValue);
                                break;
                            case TFParameterTargetType.Boolean:
                                fieldInfo.SetValue(component, value.boolValue);
                                break;
                            default:
                                throw new ArgumentOutOfRangeException();
                        }
                    }
                }

                foreach (var (obj, fieldified) in _fieldifications)
                {
                    var fieldInfo = generatedType.GetField(fieldified, BindingFlags.Instance | BindingFlags.NonPublic);
                    if (fieldInfo != null) // Defensive. This may be null if we haven't recompiled the class yet.
                    {
                        fieldInfo.SetValue(component, obj);
                    }
                }
            }
        }

        private void ProcessEvents(TFSection tfMethods)
        {
            // TODO: Events need to be added as functions of this class

            for (var index = 0; index < _behaviour.events.Count; index++)
            {
                var tfEvent = _behaviour.events[index];

                var tfMethod = new TFBrace($"{__PublicKeyword} void {tfEvent.eventName}()");
                foreach (var instruction in tfEvent.instructions)
                {
                    var instructionParametersAsCode = string.Join(", ", instruction.parameters
                        .Select(parameter =>
                        {
                            if (parameter.isVariableOrField)
                            {
                                // TODO: Verify that the symbol accepts that type
                                // return SanitizeVariableOrFieldName(parameter.identifier);
                                return parameter.identifierInternalGuid == "" ? "null" : GuidToVariableOrField(parameter.identifierInternalGuid);
                            }
                            else
                            {
                                return ValueAsCode(parameter);
                            }
                        }));

                    var line = instruction.isStatic
                        ? $"{instruction.identifier}({instructionParametersAsCode})"
                        // FIXME: Non-static should not imply object value
                        : $"{Fieldificate(instruction.self.value.objectValue, ref instruction.fieldifiedIdentifier)}.{instruction.identifier}({instructionParametersAsCode})";

                    var instructionAssignTo = SanitizeVariableOrFieldName(instruction.assignTo);
                    if (instruction.hasReturnValue && !string.IsNullOrWhiteSpace(instructionAssignTo))
                    {
                        tfMethod.Add(new TFLine($"var {instructionAssignTo} = {line};"));
                    }
                    else
                    {
                        tfMethod.Add(new TFLine($"{line};"));
                    }
                }

                tfMethods.Add(tfMethod);

                if (index < _behaviour.events.Count - 1)
                {
                    tfMethods.Add(new TFEmptyLine());
                }
            }
        }

        private string GuidToVariableOrField(string parameterIdentifierInternalGuid)
        {
            // FIXME: Sanity checks
            return SanitizeVariableOrFieldName(_behaviour.fields.First(field => field.internalGuid == parameterIdentifierInternalGuid).name);
        }

        private string ValueAsCode(TFParameter parameter)
        {
            var value = parameter.value;
            switch (value.targetType)
            {
                case TFParameterTargetType.String: return $"\"{SanitizeStringValue(value.stringValue)}\"";
                case TFParameterTargetType.Object: return Fieldificate(value.objectValue, ref parameter.fieldifiedIdentifier);
                case TFParameterTargetType.Boolean: return value.boolValue ? "true" : "false";
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        private string SanitizeStringValue(string input)
        {
            return input
                .Replace("\n", "\\n")
                .Replace("\r", "")
                .Replace("\"", @"\""");
        }

        private string Fieldificate(Object objectToFieldify, ref string fieldifiedIdentifier)
        {
            if (_fieldifications.TryGetValue(objectToFieldify, out var stored)) return stored;

            if (string.IsNullOrWhiteSpace(fieldifiedIdentifier) || !fieldifiedIdentifier.StartsWith(FieldifiedPrefix))
            {
                // This is unstable, hence we're storing it immediately through the ref parameter.
                var unstableIdentifier = Guid.NewGuid().ToString();
                fieldifiedIdentifier = $"{FieldifiedPrefix}{H12Utilities.SimpleSha1(unstableIdentifier)}";
            }

            _fieldifications.Add(objectToFieldify, fieldifiedIdentifier);
            var label = objectToFieldify == null ? "null" : objectToFieldify.name;
            _fieldificationMetadata.Add(objectToFieldify, $"{label}");

            return fieldifiedIdentifier;
        }
    }

    internal interface ITFElt
    {
    }

    internal class TFRoot
    {
        internal List<ITFElt> Elements { get; } = new List<ITFElt>();

        internal TFRoot Add(ITFElt elt)
        {
            Elements.Add(elt);
            return this;
        }
    }

    internal class TFBrace : ITFElt
    {
        internal string HeaderNullableOrEmpty { get; }
        internal List<ITFElt> Elements { get; } = new List<ITFElt>();

        internal TFBrace(string headerNullableOrEmpty)
        {
            HeaderNullableOrEmpty = headerNullableOrEmpty;
        }

        internal TFBrace Add(ITFElt elt)
        {
            Elements.Add(elt);
            return this;
        }
    }

    internal class TFSection : ITFElt
    {
        internal List<ITFElt> Elements { get; } = new List<ITFElt>();

        internal TFSection()
        {
        }

        internal TFSection Add(ITFElt elt)
        {
            Elements.Add(elt);
            return this;
        }
    }

    internal class TFLine : ITFElt
    {
        internal string Line { get; }

        internal TFLine(string line)
        {
            Line = line;
        }
    }

    internal class TFEmptyLine : ITFElt
    {
    }

    internal class TFUnindentedLine : ITFElt
    {
        internal string Line { get; }

        internal TFUnindentedLine(string line)
        {
            Line = line;
        }
    }
}
